//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signup_Login.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "First Name is required Field")]
        [DisplayName("First Name")]
       
        public string FirstName { get; set; }
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Last Name is required Field")]
        public string LastName { get; set; }
        [DisplayName("Gender")]
        [Required(ErrorMessage = "Gender is required Field")]
        public string gender { get; set; }
        [DisplayName("Age")]
        [Required(ErrorMessage = "Age is required Field")]
        public int age { get; set; }
        [DisplayName("Email")]
        [EmailAddress]
        [Required(ErrorMessage = "Email is required Field")]
        public string email { get; set; }
        [DisplayName("UserName")]
        [Required(ErrorMessage = "UserName is required Field")]
        public string username { get; set; }
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password is required Field")]
        public string password { get; set; }
        [DisplayName("Confirm Password")]
        [DataType(DataType.Password)]
      
        [Required(ErrorMessage = "Confirm Password is required Field")]
        [Compare("password", ErrorMessage = "Password not match")]
        public string confirm_password { get; set; }
    }
}
