//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
using System.ComponentModel.DataAnnotations;

namespace InventoryTrackingSystem.Models
{
    public class User
    {
        [Key]
        public int UserID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Password { get; set; }
        public string Role { get; set; } 
    }
}

